package org.ua.wohnung.bot.flows.step

enum class FlowStep {
    INITIAL,
    CONVERSATION_START,
    ACCEPT_POLICIES,
    PERSONAL_DATA_PROCESSING_APPROVAL,
    BUNDESLAND_SELECTION,
    DISTRICT_SELECTION,
    FAMILY_COUNT,
    FAMILY_MEMBERS,
    FIRSTNAME_AND_LASTNAME,
    PHONE_NUMBER,
    WBS,
    WBS_DETAILS,
    EMAIL,
    PETS,
    FOREIGN_LANGUAGES,
    READY_TO_MOVE,
    ALLERGIES,

    CONVERSATION_FINISH_REMOVAL,

    GUEST_USER_REGISTRATION_FINISHED_SUCCESS,
    FORWARD_TO_WEB,

    CONDITIONS,
    NO_USER_NAME_ERROR,

    REGISTRATION_INCOMPLETE_ERROR,

    CONVERSATION_FINISHED_DECLINED,
    REGISTERED_USER_INIT,
    REGISTERED_USER_CONVERSATION_START,
    REGISTERED_USER_LIST_APARTMENTS,

    REGISTERED_USER_APPLY_FOR_APARTMENT,
    REGISTERED_USER_REQUEST_RECEIVED,
    REGISTERED_USER_REQUEST_DECLINED,

    REGISTERED_USER_NO_APARTMENTS_AVAILABLE,

    ADMIN_START,
    ADMIN_LIST_APPLICANTS,
    ADMIN_APARTMENT_INFO_ASK_APARTMENT_ID,
    ADMIN_GET_USER_INFO,
    ADMIN_WHO_IS_INTERESTED_ASK_APARTMENT_ID,

    OWNER_START,
    OWNER_APARTMENTS_LOADED,
    OWNER_ADD_ADMIN,
    OWNER_REMOVE_ADMIN,
    OWNER_LIST_ADMINS,
    OWNER_ADD_ADMIN_DONE;
}
