spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wohnungsbot
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jooq:
    sql:
      dialect: POSTGRES
