package org.ua.wohnung.bot.flows

enum class FlowStep {
    CONVERSATION_START,
    ACCEPT_POLICIES,
    PERSONAL_DATA_PROCESSING_APPROVAL,
    BUNDESLAND_SELECTION,
    FAMILY_COUNT,
    FIRSTNAME_AND_LASTNAME,
    PHONE_NUMBER,
    PETS,
    REGISTRATION_FINISHED_SUCCESS,
    CONVERSATION_FINISHED_DECLINED,

    REGISTERED_USER_CONVERSATION_START,
    REGISTERED_USER_LIST_APARTMENTS,
    CONVERSATION_FINISH_REMOVAL,

    OWNER_START,
    OWNER_APARTMENTS_LOADED,
    OWNER_ADD_ADMIN,
    OWNER_REMOVE_ADMIN,
    OWNER_LIST_ADMINS,
    OWNER_ADD_ADMIN_DONE;
}
