package org.ua.wohnung.bot.flows.userregistration

enum class FlowStep {
    CONVERSATION_START,
    ACCEPT_POLICIES,
    PERSONAL_DATA_PROCESSING_APPROVAL,
    BUNDESLAND_SELECTION,
    FAMILY_COUNT,
    FIRSTNAME_AND_LASTNAME,
    PHONE_NUMBER,
    PETS,
    CONVERSATION_FINISHED_SUCCESS,
    CONVERSATION_FINISHED_DECLINED,
    CONVERSATION_FINISH_REMOVAL
}
